version: '2'
services:
  db:
    image: postgres
  api:
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - db
  front:
    build: ./front
    command: npm start
    volumes: 
      - ./front:/app/front
    ports:
      - "3000:3000"
    depends_on:
      - api
